#!/usr/bin/env node
/*
  store-meta — the page copy for a game, generated from its manifest.

    node tools/publish/store-meta.mjs --game=vipera
    node tools/publish/store-meta.mjs --all
    node tools/publish/store-meta.mjs --game=vipera --out=dist/meta

  butler uploads a build; it cannot touch the page around it. Title, taglines,
  description, tags, the embed size and the "mobile friendly" checkbox have no
  public API — they are filled in by hand, once per game, in the itch form.

  So this tool does not publish anything: it prints exactly what goes into that
  form, taken from games/<slug>/manifest.json, which is the single source of
  truth for it. Nobody rewrites a tagline in a second place, and two outlets
  cannot drift apart.

  The same text is what a store listing needs later (phase 8), which is why
  this lives in tools/publish/ and not in the itch script.
*/

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const argv = process.argv.slice(2);
const only = (argv.find((a) => a.startsWith('--game=')) || '').split('=')[1] || null;
const outDir = (argv.find((a) => a.startsWith('--out=')) || '').split('=')[1] || null;
const all = argv.includes('--all');

if (!only && !all) {
  console.error('usage: store-meta.mjs --game=<slug> | --all   [--out=<dir>]');
  process.exit(1);
}

function slugs() {
  if (only) return [only];
  return readdirSync(path.join(ROOT, 'games'), { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .filter((s) => existsSync(path.join(ROOT, 'games', s, 'manifest.json')))
    .sort();
}

async function manifestOf(slug) {
  const file = path.join(ROOT, 'games', slug, 'manifest.json');
  if (!existsSync(file)) throw new Error(`${slug}: no manifest.json`);
  return JSON.parse(await readFile(file, 'utf8'));
}

// itch tags are matched against existing ones, which are lowercase and short.
function tagLine(copy) {
  if (!copy || !Array.isArray(copy.tags)) return '—';
  return copy.tags.map((t) => t.toLowerCase()).join(', ');
}

function section(title, body) {
  return `## ${title}\n\n${body || '—'}\n`;
}

function render(m) {
  const itch = m.itch || {};
  const vp = Array.isArray(itch.viewport) ? itch.viewport : [450, 800];
  const en = (m.copy && m.copy.en) || {};
  const fr = (m.copy && m.copy.fr) || {};
  const project = itch.project || m.slug;
  const user = itch.user || 'newrare';
  const channel = itch.channel || 'html5';

  /* The two fields itch itself calls "short description" and "description".
     The long one is the manifest's `description`, written in English, which is
     the same text the site's gallery shows. */
  return [
    `# ${m.title || m.slug} — itch.io page`,
    '',
    `Generated by \`node tools/publish/store-meta.mjs --game=${m.slug}\` from`,
    `games/${m.slug}/manifest.json. Paste it into the itch form; nothing here is`,
    'pushed automatically, because itch has no public API for a page.',
    '',
    section('Title', m.title || m.slug),
    section('Short description (EN)', en.tagline || m.tagline),
    section('Short description (FR)', fr.tagline),
    section('Description', m.description),
    section('Tags (EN)', tagLine(en)),
    section('Tags (FR)', tagLine(fr)),
    section('Embed', [
      'Kind of project: **HTML**',
      'Embed in page, with a fullscreen button',
      `Viewport: **${vp[0]} × ${vp[1]}** (portrait, the game is authored at 720×1280)`,
      `Mobile friendly: **${itch.mobileFriendly === false ? 'no' : 'yes'}**`,
      'Automatically start on page load: **no** (the menu is the first screen)',
      'Enable scrollbars: **no**'
    ].join('  \n')),
    section('Colours', [
      `Background: \`${(m.theme && m.theme.bg) || '#0a0a1c'}\``,
      `Accent: \`${(m.theme && m.theme.accent) || '—'}\``
    ].join('  \n')),
    section('Build', [
      '```bash',
      `node tools/build/build.mjs --target=web --dest=itch --game=${m.slug}`,
      `node tools/publish/deploy-itch.mjs --game=${m.slug}                      # → ${user}/${project}:html5-dev`,
      `node tools/publish/deploy-itch.mjs --game=${m.slug} --channel=${channel}   # the public channel`,
      '```'
    ].join('\n')),
    section('Classification', [
      'Release status: **Released**',
      'Pricing: **free**, no payments',
      'Genre: **Action**',
      'Input: touch, mouse, keyboard'
    ].join('  \n'))
  ].join('\n');
}

async function main() {
  for (const slug of slugs()) {
    const m = await manifestOf(slug);
    const text = render(m);
    if (outDir) {
      const dir = path.join(ROOT, outDir);
      await mkdir(dir, { recursive: true });
      const file = path.join(dir, `${slug}.md`);
      await writeFile(file, text);
      console.log(`wrote ${path.relative(ROOT, file)}`);
    } else {
      process.stdout.write(text + '\n');
    }
  }
}

main().catch((err) => { console.error('store-meta failed:', err.message); process.exit(1); });
